math_commands = [
    ("\\alpha", ),
    ("\\beta", ),
    ("\\gamma", ),
    ("\\delta", ),
    ("\\epsilon", ),
    ("\\varepsilon", ),
    ("\\zeta", ),
    ("\\eta", ),
    ("\\theta", ),
    ("\\vartheta", ),
    ("\\iota", ),
    ("\\kappa", ),
    ("\\lambda", ),
    ("\\mu", ),
    ("\\nu", ),
    ("\\xi", ),
    ("\\pi", ),
    ("\\rho", ),
    ("\\varrho", ),
    ("\\sigma", ),
    ("\\tau", ),
    ("\\upsilon", ),
    ("\\phi", ),
    ("\\varphi", ),
    ("\\chi", ),
    ("\\psi", ),
    ("\\omega", ),
    ("\\digamma", ),
    ("\\Gamma", ),
    ("\\Delta", ),
    ("\\Theta", ),
    ("\\Lambda", ),
    ("\\Xi", ),
    ("\\Pi", ),
    ("\\Sigma", ),
    ("\\Phi", ),
    ("\\Psi", ),
    ("\\Omega", ),

    ("\\infty", ),
    ("\\varnothing", ),

    ("\\quad", ),
    ("\\qquad", ),
    ("\\nonumber", ),

    ("\\bigcup", ),
    ("\\bigcap", ),
    ("\\langle", ),
    ("\\rangle", ),
    ("\\bigcup", ),
    ("\\bigcap", ),
    ("\\wedge", ),

    ("\\leftarrow", ),
    ("\\longleftarrow", ),
    ("\\Leftarrow", ),
    ("\\Longleftarrow", ),
    ("\\rightarrow", ),
    ("\\longrightarrow", ),
    ("\\Rightarrow", ),
    ("\\Longrightarrow", ),
    ("\\leftrightarrow", ),
    ("\\longleftrightarrow", ),
    ("\\Leftrightarrow", ),
    ("\\Longleftrightarrow", ),
    ("\\uparrow", ),
    ("\\downarrow", ),

    ("\\mathit", ),
    ("\\mathbf", ),
    ("\\mathbb", ),
    ("\\mathrm", ),
    ("\\mathsf", ),
    ("\\mathcal", ),

    ("\\partial", ),

    ("\\hat{}", "hat{$1}$0"),
    ("\\bar{}", "bar{$1}$0"),
    ("\\tilde{}", "tilde{$1}$0"),
    ("\\widehat{}", "widehat{$1}$0"),
    ("\\overline{}", "overline{$1}$0"),

    ("\\sum_{}^{}", "sum_{$1}^{$2}$0"),
    ("\\prod_{}^{}", "prod_{$1}^{$2}$0"),
    ("\\int_{}^{}", "int_{$1}^{$2}$0"),
    ("\\frac{}{}", "frac{$1}{$2}$0"),
    ("\\overset{}{}", "overset{$1}{$2}$0"),
    ("\\overbrace{}{}", "overbrace{$1}{$2}$0"),
    ("\\underset{}{}", "underset{$1}{$2}$0"),
    ("\\underbrace{}{}", "underbrace{$1}{$2}$0"),

    ("\\binom{}{}", "binom{$1}{$2}$0"),
    ("\\text{}", "text{$1}$0")
]

general_commands = [
    ("\\usagepacage", ),
    ("\\includegraphics", ),
    ("\\part{}", "part{$1}"),
    ("\\part*{}", "part*{$1}"),
    ("\\chapter{}", "chapter{$1}"),
    ("\\chapter*{}", "chapter*{$1}"),
    ("\\section{}", "section{$1}"),
    ("\\section*{}", "section*{$1}"),
    ("\\subsection{}", "subsection{$1}"),
    ("\\subsection*{}", "subsection*{$1}"),

    ("\\underline{}", "underline{$1}"),
    ("\\textbf{}", "textbf{$1}"),
    ("\\texttt{}", "texttt{$1}"),
    ("\\textit{}", "textit{$1}"),

    ("\\bibliographystyle{}", "bibliographystyle{$1}"),
    ("\\bibliography{}", "bibliography{$1}"),
    ("\\addbibresource{}", "addbibresource{$1}")
]


arrow_map = {
    "<-": "\\leftarrow",
    "<--": "\\longleftarrow",
    "->": "\\rightarrow",
    "-->": "\\longrightarrow",
    "<->": "\\leftrightarrow",
    "<-->": "\\longleftrightarrow",
    "<=": "\\Leftarrow",
    "<==": "\\Longleftarrow",
    "=>": "\\Rightarrow",
    "==>": "\\Longrightarrow",
    "<=>": "\\Leftrightarrow",
    "<==>": "\\Longleftrightarrow"
}
