#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright (C) 2010 Jose Aliste <jose.aliste@gmail.com>
#               2011 Benjamin Kellermann <Benjamin.Kellermann@tu-dresden.de>
#               2016 Randy Lai <randy.cs.lai@gmail.com>
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public Licence as published by the Free Software
# Foundation; either version 2 of the Licence, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public Licence for more
# details.
#
# You should have received a copy of the GNU General Public Licence along with
# this program; if not, write to the Free Software Foundation, Inc., 51 Franklin
# Street, Fifth Floor, Boston, MA  02110-1301, USA

# This file offers forward search for evince.

import dbus
import sys
import os
import time
import traceback

if sys.version_info >= (3, 0, 0):
    from urllib.parse import quote
else:
    from urllib import quote


def print_usage():
    print('Usage: evince_forward_search pdf_file line_number tex_file')
    sys.exit(1)

if len(sys.argv) != 4:
    print_usage()

pdf = os.path.abspath(sys.argv[1]).replace(" ", "%20")
line = int(sys.argv[2])
tex = os.path.join(
        os.path.dirname(os.path.abspath(sys.argv[3])),
        './',
        os.path.basename(os.path.abspath(sys.argv[3])))

try:
    bus = dbus.SessionBus()
    daemon = bus.get_object('org.gnome.evince.Daemon', '/org/gnome/evince/Daemon')
    dbus_name = daemon.FindDocument(
        'file://' + quote(pdf, safe="%/:=&?~#+!$,;'@()*[]"),
        True, dbus_interface='org.gnome.evince.Daemon')
    window = bus.get_object(dbus_name, '/org/gnome/evince/Window/0')
    time.sleep(0.2)
    window.SyncView(tex, (line, 1), 0, dbus_interface='org.gnome.evince.Window')
except dbus.DBusException:
    traceback.print_exc()
