<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>tex</string>
	</array>
	<key>foldingStartMarker</key>
	<string>\\begin\{.*\}|%.*\(fold\)\s*$</string>
	<key>foldingStopMarker</key>
	<string>\\end\{.*\}|%.*\(end\)\s*$</string>
	<key>keyEquivalent</key>
	<string>^~L</string>
	<key>name</key>
	<string>LaTeX Extended</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>%</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>comment.latex</string>
						</dict>
					</dict>
					<key>end</key>
					<string>$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>.</string>
							<key>name</key>
							<string>comment.latex</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>&amp;</string>
			<key>name</key>
			<string>variable.other.latex</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#special</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\\(?:re)?newcommand){\s*([^\}]*)\s*}[^{]*{</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.latex</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.function.latex</string>
				</dict>
			</dict>
			<key>end</key>
			<string>}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#option</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\\begin)\{\s*((?:align|alignat|displaymath|displaymath|eqnarray|equation|flalign|gather|math|multline|xalignat)\*?)\s*\}</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.latex</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.latex</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\\end)\{\s*(\2)\s*\}</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.latex</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.latex</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.definition.math.latex</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#math</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\$\$|\$)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.other.latex</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\1)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.other.latex</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.definition.math.latex</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#special</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#math</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\\\[)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.latex</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\\\])</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.latex</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.definition.math.latex</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#math</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\\\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.latex</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\\\))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.latex</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.definition.math.latex</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#math</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\\begin)\{\s*((?:itemize|enumerate|description)\*?)\s*\}</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.latex</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.latex</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\\end)\{\s*(\2)\s*\}</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.latex</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.latex</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.definition.list.latex</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\\begin)\{\s*((?:[vV]erbatim)\*?)\s*\}</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.latex</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.latex</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\\end)\{\s*(\2)\s*\}</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.latex</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.latex</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.definition.verbatim.latex</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.latex</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\\verb)(\W)(.*?)\2</string>
			<key>name</key>
			<string>meta.definition.verbatim.latex</string>
		</dict>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#ref</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#label</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#beginend</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#section</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#command</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#braces</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>beginend</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.latex</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.latex</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\\begin)\{\s*(\w*)\*?\s*\}</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.latex</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.latex</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\\end)\{\s*(\w*)\*?\s*\}</string>
				</dict>
			</array>
		</dict>
		<key>label</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(\\label){</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.latex</string>
						</dict>
					</dict>
					<key>end</key>
					<string>}</string>
					<key>name</key>
					<string>meta.definition.label.latex</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>[a-zA-Z0-9]</string>
							<key>name</key>
							<string>string.other.latex</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>option_braces</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\{</string>
					<key>end</key>
					<string>\}</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#option</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>option</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#option_braces</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#beginend</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#command</string>
				</dict>
			</array>
		</dict>
		<key>special</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\(%|\$|#|&amp;|\{|\})</string>
					<key>name</key>
					<string>variable.other.latex</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.other.latex</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.latex</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.function.latex</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\\\\)(?:\[\s*([0-9]*)\s*(\w*)\s*\])?</string>
				</dict>
			</array>
		</dict>
		<key>braces</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\{</string>
					<key>end</key>
					<string>\}</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>math</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(\\(?:(?:\w+)?text(?:\w+)?|mbox|hbox))\{</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.latex</string>
						</dict>
					</dict>
					<key>end</key>
					<string>}</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#braces</string>
						</dict>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\\parbox)\{[^\}]*\}\{</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.latex</string>
						</dict>
					</dict>
					<key>end</key>
					<string>}</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#braces</string>
						</dict>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#label</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#beginend</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\[a-zA-Z]+</string>
					<key>name</key>
					<string>support.function.latex</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\+|\-|=|-|\*|/|\^|_|&lt;|&gt;|\\\{|\\\}|\[|\]|\(|\)</string>
					<key>name</key>
					<string></string>
				</dict>
				<dict>
					<key>match</key>
					<string>[a-zA-Z]+</string>
					<key>name</key>
					<string>keyword.other</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[0-9]+</string>
					<key>name</key>
					<string>constant.numeric.latex</string>
				</dict>
			</array>
		</dict>
		<key>ref</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(\\(?:(?:eq|page)?ref|cite\w*\*?))(\[.*?\]){0,2}{</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.latex</string>
						</dict>
					</dict>
					<key>end</key>
					<string>}</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>[a-zA-Z0-9]</string>
							<key>name</key>
							<string>string.other.latex</string>
						</dict>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>section</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\\((?:sub)*(?:section|chapter))(\*)?\{</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.function</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\}</string>
					<key>name</key>
					<string>meta.definition.section.latex</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>command</key>
		<dict>
			<key>match</key>
			<string>\\[a-zA-Z]+(?:\s|\n?)?</string>
			<key>name</key>
			<string>support.function.latex</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.tex.latex</string>
	<key>uuid</key>
	<string>3BEEA00C-6B1D-11D9-B8AD-000D93589AF6</string>
</dict>
</plist>
