math_commands = [
    ("\\alpha",),
    ("\\beta",),
    ("\\gamma",),
    ("\\delta",),
    ("\\epsilon",),
    ("\\varepsilon",),
    ("\\zeta",),
    ("\\eta",),
    ("\\theta",),
    ("\\vartheta",),
    ("\\iota",),
    ("\\kappa",),
    ("\\varkappa",),
    ("\\lambda",),
    ("\\mu",),
    ("\\nu",),
    ("\\xi",),
    ("\\pi",),
    ("\\rho",),
    ("\\varrho",),
    ("\\sigma",),
    ("\\varsigma",),
    ("\\tau",),
    ("\\upsilon",),
    ("\\phi",),
    ("\\varphi",),
    ("\\chi",),
    ("\\psi",),
    ("\\omega",),
    ("\\digamma",),
    ("\\Gamma",),
    ("\\Delta",),
    ("\\Theta",),
    ("\\Lambda",),
    ("\\Xi",),
    ("\\Pi",),
    ("\\Sigma",),
    ("\\Phi",),
    ("\\Psi",),
    ("\\Omega",),
    ("\\big",),
    ("\\Big",),
    ("\\bigg",),
    ("\\Bigg",),
    ("\\quad",),
    ("\\qquad",),
    ("\\nonumber",),
    ("\\bigcup",),
    ("\\bigcap",),
    ("\\mathnormal",),
    ("\\mathrm",),
    ("\\mathit",),
    ("\\mathbf",),
    ("\\mathsf",),
    ("\\mathtt",),
    ("\\mathfrak",),
    ("\\mathcal",),
    ("\\mathbb",),
    ("\\mathscr",),
    ("\\text{}", "text{$0}"),
    ("\\hat",),
    ("\\bar",),
    ("\\tilde",),
    ("\\widehat{}", "\\widehat{$0}"),
    ("\\widetilde{}", "\\widetilde{$0}"),
    ("\\overbrace{}{}", "\\overbrace{$1}{$0}"),
    ("\\underbrace{}{}", "\\underbrace{$1}{$0}"),
    ("\\overrightarrow{}", "\\overrightarrow{$0}"),
    ("\\overleftarrow{}", "\\overleftarrow{$0}"),
    ("\\longleftarrow",),
    ("\\Longleftarrow",),
    ("\\longrightarrow",),
    ("\\Longrightarrow",),
    ("\\longleftrightarrow",),
    ("\\Longleftrightarrow",),
    ("\\sum_{}^{}", "\\sum_{$1}^{$0}"),
    ("\\prod_{}^{}", "\\prod_{$1}^{$0}"),
    ("\\int_{}^{}", "\\int_{$1}^{$0}"),
    ("\\iint_{}^{}", "\\iint_{$1}^{$0}"),
    ("\\iiint_{}^{}", "\\iiint_{$1}^{$0}"),
    ("\\iiiint_{}^{}", "\\iiiint_{$1}^{$0}"),
    ("\\idotsint{}^{}", "\\idotsint{$1}^{$0}"),
    ("\\oint_{}^{}", "\\oint_{$1}^{$0}"),
    ("\\frac{}{}", "\\frac{$1}{$0}"),
    ("\\binom{}{}", "\\binom{$1}{$0}"),
    ("\\overset{}{}", "\\overset{$1}{$0}"),
    ("\\underset{}{}", "\\underset{$1}{$0}"),
    ("\\Box",),
    ("\\Downarrow",),
    ("\\Im",),
    ("\\Leftrightarrow",),
    ("\\Re",),
    ("\\Rightarrow",),
    ("\\Uparrow",),
    ("\\Upsilon",),
    ("\\aleph",),
    ("\\amalg",),
    ("\\angle",),
    ("\\approx",),
    ("\\arccos",),
    ("\\arccot",),
    ("\\arcsin",),
    ("\\arctan",),
    ("\\ast",),
    ("\\asymp",),
    ("\\backslash",),
    ("\\beth",),
    ("\\bigcirc",),
    ("\\bigtriangledown",),
    ("\\bigtriangleup",),
    ("\\bot",),
    ("\\bowtie",),
    ("\\bullet",),
    ("\\cap",),
    ("\\cdot",),
    ("\\circ",),
    ("\\cong",),
    ("\\cos",),
    ("\\cosh",),
    ("\\cot",),
    ("\\coth",),
    ("\\csc",),
    ("\\cup",),
    ("\\dagger",),
    ("\\dashv",),
    ("\\ddagger",),
    ("\\diamond",),
    ("\\displaystyle",),
    ("\\div",),
    ("\\doteq",),
    ("\\downarrow",),
    ("\\ell",),
    ("\\emptyset",),
    ("\\equiv",),
    ("\\eth",),
    ("\\exists",),
    ("\\forall",),
    ("\\frown",),
    ("\\geq",),
    ("\\gets",),
    ("\\gg",),
    ("\\gimel",),
    ("\\hbar",),
    ("\\iff",),
    ("\\imath",),
    ("\\implies",),
    ("\\in",),
    ("\\infty",),
    ("\\jmath",),
    ("\\land",),
    ("\\langle",),
    ("\\lceil",),
    ("\\leftarrow",),
    ("\\leftrightarrow",),
    ("\\leq",),
    ("\\lfloor",),
    ("\\ll",),
    ("\\lor",),
    ("\\mapsto",),
    ("\\measuredangle",),
    ("\\mid",),
    ("\\models",),
    ("\\mp",),
    ("\\nabla",),
    ("\\neg",),
    ("\\neq",),
    ("\\nexists",),
    ("\\ni",),
    ("\\notin",),
    ("\\nparallel",),
    ("\\nsubseteq",),
    ("\\nsupseteq",),
    ("\\odot",),
    ("\\ominus",),
    ("\\operatorname",),
    ("\\oplus",),
    ("\\oslash",),
    ("\\otimes",),
    ("\\parallel",),
    ("\\partial",),
    ("\\perp",),
    ("\\pm",),
    ("\\prec",),
    ("\\preceq",),
    ("\\propto",),
    ("\\rangle",),
    ("\\rceil",),
    ("\\rfloor",),
    ("\\rightarrow",),
    ("\\rightleftharpoons",),
    ("\\sec",),
    ("\\setminus",),
    ("\\sim",),
    ("\\simeq",),
    ("\\sin",),
    ("\\sinh",),
    ("\\smile",),
    ("\\sphericalangle",),
    ("\\sqcap",),
    ("\\sqcup",),
    ("\\sqsubset",),
    ("\\sqsubseteq",),
    ("\\sqsupset",),
    ("\\sqsupseteq",),
    ("\\star",),
    ("\\subset",),
    ("\\subseteq",),
    ("\\succ",),
    ("\\succeq",),
    ("\\supset",),
    ("\\supseteq",),
    ("\\tan",),
    ("\\tanh",),
    ("\\therefore",),
    ("\\times",),
    ("\\to",),
    ("\\top",),
    ("\\triangleleft",),
    ("\\triangleright",),
    ("\\uparrow",),
    ("\\uplus",),
    ("\\varnothing",),
    ("\\varpi",),
    ("\\vdash",),
    ("\\vee",),
    ("\\wedge",),
    ("\\wp",),
    ("\\wr",)
]

general_commands = [
    ("\\usepackage",),
    ("\\includegraphics",),
    ("\\part{}", "\\part{$0}"),
    ("\\part*{}", "\\part*{$0}"),
    ("\\chapter{}", "\\chapter{$0}"),
    ("\\chapter*{}", "\\chapter*{$0}"),
    ("\\section{}", "\\section{$0}"),
    ("\\section*{}", "\\section*{$0}"),
    ("\\subsection{}", "\\subsection{$0}"),
    ("\\subsection*{}", "\\subsection*{$0}"),
    ("\\subsubsection{}", "\\subsubsection{$0}"),
    ("\\subsubsection*{}", "\\subsubsection*{$0}"),
    ("\\underline{}", "\\underline{$0}"),
    ("\\overline{}", "\\overline{$0}"),
    ("\\bibliographystyle",),
    ("\\bibliography",),
    ("\\addbibresource",),
    ("\\Huge",),
    ("\\LARGE",),
    ("\\LaTeX",),
    ("\\LaTeXe",),
    ("\\Large",),
    ("\\TeX",),
    ("\\addcontentsline",),
    ("\\address",),
    ("\\addtocontents",),
    ("\\addtocounter",),
    ("\\addtolength",),
    ("\\addvspace",),
    ("\\alph",),
    ("\\appendix",),
    ("\\arabic",),
    ("\\author",),
    ("\\author{}", "\\\\author{$0}"),
    ("\\baselineskip",),
    ("\\baselinestretch",),
    ("\\bfseries",),
    ("\\bibitem",),
    ("\\bigskip",),
    ("\\bigskipamount",),
    ("\\boldmath",),
    ("\\boldsymbol",),
    ("\\cal",),
    ("\\caption",),
    ("\\cdots",),
    ("\\centering",),
    ("\\circle",),
    ("\\cite",),
    ("\\cleardoublepage",),
    ("\\clearpage",),
    ("\\cline",),
    ("\\closing",),
    ("\\color",),
    ("\\copyright",),
    ("\\dashbox",),
    ("\\date",),
    ("\\ddots",),
    ("\\documentclass",),
    ("\\dotfill",),
    ("\\em",),
    ("\\emph",),
    ("\\ensuremath",),
    ("\\epigraph",),
    ("\\euro",),
    ("\\fbox",),
    ("\\fill",),
    ("\\flushbottom",),
    ("\\fnsymbol",),
    ("\\footnote",),
    ("\\footnotemark",),
    ("\\footnotesize",),
    ("\\footnotetext",),
    ("\\frame",),
    ("\\framebox",),
    ("\\frenchspacing",),
    ("\\hfill",),
    ("\\hline",),
    ("\\href",),
    ("\\hrulefill",),
    ("\\hspace",),
    ("\\huge",),
    ("\\hyphenation",),
    ("\\include",),
    ("\\includeonly",),
    ("\\indent",),
    ("\\input",),
    ("\\item",),
    ("\\itshape",),
    ("\\kill",),
    ("\\label",),
    ("\\large",),
    ("\\ldots",),
    ("\\left",),
    ("\\lefteqn",),
    ("\\line",),
    ("\\linebreak",),
    ("\\linethickness",),
    ("\\linewidth",),
    ("\\listoffigures",),
    ("\\listoftables",),
    ("\\location",),
    ("\\makebox",),
    ("\\maketitle",),
    ("\\markboth",),
    ("\\markright",),
    ("\\mathop",),
    ("\\mbox",),
    ("\\medskip",),
    ("\\multicolumn",),
    ("\\multiput",),
    ("\\newcolumntype",),
    ("\\newcommand",),
    ("\\newcounter",),
    ("\\newenvironment",),
    ("\\newfont",),
    ("\\newlength",),
    ("\\newline",),
    ("\\newpage",),
    ("\\newsavebox",),
    ("\\newtheorem",),
    ("\\nocite",),
    ("\\noindent",),
    ("\\nolinebreak",),
    ("\\nonfrenchspacing",),
    ("\\nopagebreak",),
    ("\\normalsize",),
    ("\\not",),
    ("\\onecolumn",),
    ("\\opening",),
    ("\\oval",),
    ("\\pagebreak",),
    ("\\pagenumbering",),
    ("\\pageref",),
    ("\\pagestyle",),
    ("\\par",),
    ("\\paragraph",),
    ("\\parbox",),
    ("\\parindent",),
    ("\\parskip",),
    ("\\protect",),
    ("\\providecommand",),
    ("\\put",),
    ("\\raggedbottom",),
    ("\\raggedleft",),
    ("\\raggedright",),
    ("\\raisebox",),
    ("\\ref",),
    ("\\renewcommand",),
    ("\\right",),
    ("\\rmfamily",),
    ("\\roman",),
    ("\\rule",),
    ("\\savebox",),
    ("\\sbox",),
    ("\\scriptsize",),
    ("\\scshape",),
    ("\\setcounter",),
    ("\\setlength",),
    ("\\settowidth",),
    ("\\sffamily",),
    ("\\shortstack",),
    ("\\signature",),
    ("\\signature{}", "\\\\signature{$0}"),
    ("\\slash",),
    ("\\slshape",),
    ("\\small",),
    ("\\smallskip",),
    ("\\sout",),
    ("\\space",),
    ("\\sqrt",),
    ("\\stackrel",),
    ("\\stepcounter",),
    ("\\subparagraph",),
    ("\\tableofcontents",),
    ("\\telephone",),
    ("\\textbf{}", "\\\\textbf{$0}"),
    ("\\textcolor{}{}", "\\\\textcolor{$1}{$0}"),
    ("\\textheight",),
    ("\\textit{}", "\\\\textit{$0}"),
    ("\\textmd{}", "\\\\textmd{$0}"),
    ("\\textnormal{}", "\\\\textnormal{$0}"),
    ("\\textrm{}", "\\\\textrm{$0}"),
    ("\\textsc{}", "\\\\textsc{$0}"),
    ("\\textsf{}", "\\\\textsf{$0}"),
    ("\\textsl{}", "\\\\textsl{$0}"),
    ("\\texttt{}", "\\\\texttt{$0}"),
    ("\\textup{}", "\\\\textup{$0}"),
    ("\\textwidth",),
    ("\\thanks",),
    ("\\thispagestyle",),
    ("\\tiny",),
    ("\\title",),
    ("\\title{}", "\\\\title{$0}"),
    ("\\today",),
    ("\\ttfamily",),
    ("\\twocolumn",),
    ("\\typein",),
    ("\\typeout",),
    ("\\uline",),
    ("\\unitlength",),
    ("\\usebox",),
    ("\\usecounter",),
    ("\\uwave",),
    ("\\value",),
    ("\\vbox",),
    ("\\vcenter",),
    ("\\vdots",),
    ("\\vector",),
    ("\\verb",),
    ("\\vfill",),
    ("\\vline",),
    ("\\vphantom",),
    ("\\vspace",)
]
